### ISSUE TITLE
"FATAL EXCEPTION" on Closing the app

### ISSUE THREAD

**Issue by devshahinpb** [Ayush783/readsms_plugin#2]
Hello
Fatal Exception happen when closing the app by "back button" not closing immediately from "Recent App" in Android 6
the message:

E/AndroidRuntime(15300): FATAL EXCEPTION: main
kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
E/AndroidRuntime(15300): 	at com.ayush783.readsms.ReadsmsPlugin.onDetachedFromActivity(ReadsmsPlugin.kt:78)
E/AndroidRuntime(15300): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:385)
E/AndroidRuntime(15300): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:690)
E/AndroidRuntime(15300): 	at io.flutter.embedding.android.FlutterFragment.onDetach(FlutterFragment.java:892)
E/AndroidRuntime(15300): 	at androidx.fragment.app.Fragment.performDetach(Fragment.java:3229)

**Comment by devshahinpb** [comment]
I think it's resolved
I just commented "line 78" in the file "ReadsmsPlugin.kt".
And the error didn't show again

**Comment by Ayush783** [comment]
sorry for the delay. would you like to create a PR and I will review it

**Comment by Ayush783** [comment]
fixed in version 0.1.0+3
