### ISSUE TITLE
Sensitive permission request.

### ISSUE THREAD

**Issue by Danc-0** [Ayush783/readsms_plugin#3]
It requires to use ` <uses-permission android:name="android.permission.RECEIVE_SMS" />` which is a sensitive permission under SMS or Call logs permission [https://support.google.com/googleplay/android-developer/answer/10208820?visit_id=638065569311424522-3053842914&rd=1#intended&zippy=%2Cexceptions%2Cpermitted-uses-of-the-sms-and-call-log-permissions](https://support.google.com/googleplay/android-developer/answer/10208820?visit_id=638065569311424522-3053842914&rd=1#intended&zippy=%2Cexceptions%2Cpermitted-uses-of-the-sms-and-call-log-permissions)

Wouldn't that not be an issue to release an app using this package? Thanks

**Comment by Ayush783** [comment]
Hi
I think you can declare the usage of this for appropriate use cases and get
the approval of Google Play team when uploading the app for review.
