### ISSUE TITLE
It is not working in production

### ISSUE THREAD

**Issue by tez-hub** [Ayush783/readsms_plugin#6]
This plugin only works on the emulator. When it is installed on phone, it doesn't work.

**Comment by swarupbhc** [comment]
Same issue @Ayush783 please help 

listening in debug but not in production

**Comment by Ayush783** [comment]
Hey, I wasn't ablle to reproduce this issue on my side, Can someone provide some logs. Or try going through the docs again.

**Comment by swarupbhc** [comment]
Hi sorry my issue was related to background service, and now solved. Thanks
for this amazing package and maintaining it.

**Comment by Ayush783** [comment]
Thanks for the quick update! Closing this
