### ISSUE TITLE
Add support for iOS 

### ISSUE THREAD

**Issue by ankitmhatre** [Ayush783/readsms_plugin#7]
We need this to work for iOS. Existing apps already autodetect and suggest the primary data like OTP on the keyboard top. 
I assume it should not be super hard.

**Comment by ankitmhatre** [comment]
iOS seems to restrict reading SMS a bit difficult. https://developer.apple.com/app-store/review/guidelines/

**Comment by Ayush783** [comment]
There is no alternate library in iOS like Telecom is in Android. So it's currently not possible.
